name: ci

on: [ push ]

jobs:
  ci:
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        target: [ test, lint ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ~1.17.1
    - name: run ${{ matrix.target }}
      run: make ${{ matrix.target }}
